name: flingon_assister
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter

  xml: any
  material_search: any

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - klingon-assistant/KlingonAssistant/data/mem-00-header.xml
    - klingon-assistant/KlingonAssistant/data/mem-01-b.xml
    - klingon-assistant/KlingonAssistant/data/mem-02-ch.xml
    - klingon-assistant/KlingonAssistant/data/mem-03-D.xml
    - klingon-assistant/KlingonAssistant/data/mem-04-gh.xml
    - klingon-assistant/KlingonAssistant/data/mem-05-H.xml
    - klingon-assistant/KlingonAssistant/data/mem-06-j.xml
    - klingon-assistant/KlingonAssistant/data/mem-07-l.xml
    - klingon-assistant/KlingonAssistant/data/mem-08-m.xml
    - klingon-assistant/KlingonAssistant/data/mem-09-n.xml
    - klingon-assistant/KlingonAssistant/data/mem-10-ng.xml
    - klingon-assistant/KlingonAssistant/data/mem-11-p.xml
    - klingon-assistant/KlingonAssistant/data/mem-12-q.xml
    - klingon-assistant/KlingonAssistant/data/mem-13-Q.xml
    - klingon-assistant/KlingonAssistant/data/mem-14-r.xml
    - klingon-assistant/KlingonAssistant/data/mem-15-S.xml
    - klingon-assistant/KlingonAssistant/data/mem-16-t.xml
    - klingon-assistant/KlingonAssistant/data/mem-17-tlh.xml
    - klingon-assistant/KlingonAssistant/data/mem-18-v.xml
    - klingon-assistant/KlingonAssistant/data/mem-19-w.xml
    - klingon-assistant/KlingonAssistant/data/mem-20-y.xml
    - klingon-assistant/KlingonAssistant/data/mem-21-a.xml
    - klingon-assistant/KlingonAssistant/data/mem-22-e.xml
    - klingon-assistant/KlingonAssistant/data/mem-23-I.xml
    - klingon-assistant/KlingonAssistant/data/mem-24-o.xml
    - klingon-assistant/KlingonAssistant/data/mem-25-u.xml
    - klingon-assistant/KlingonAssistant/data/mem-26-suffixes.xml
    - klingon-assistant/KlingonAssistant/data/mem-27-extra.xml
    - klingon-assistant/KlingonAssistant/data/mem-28-footer.xml

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  fonts:
    - family: RobotoSlab
      fonts:
        - asset: assets/fonts/RobotoSlab-Regular.ttf
